# Generated by Django 5.1.2 on 2024-10-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteCustomConfigs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bankrupt_status",
                    models.CharField(default="Bankrupt Status", max_length=512),
                ),
                ("is_bankrupt", models.BooleanField(default=False)),
            ],
        ),
    ]
